### ISSUE TITLE
Konzept zum Charaktereditor L03

### ISSUE THREAD

**Issue by obiwan1337** [TobMer/EIA2#1]
Dein Use Case Diagramm ist gut verständlich und soweit ohne syntaktische Fehler(mir fällt nichts auf)
Dein Interface Diagramm ist sehr ausführlich und mit allen Tagnamen versehen und schon durch überlegt mit welchen Nametags die verschiedenen Input-Elemente beschriftet sind. Sehr Gut.

Bei Deinem Aktivitätsdiagramm darfst du gerne mehr als eine Seite voll quetschen. 
Dazu sind auch noch ein paar Unklarheiten. Ein paar Funktionsnamen sind nicht auffindbar für mich und im rechten unteren Eck sind 2 Pfeile von einem Aktivitätsblubber weg. (Die vier Print row Sachen). Das impliziert, die beiden werden gleichzeitig ausgeführt. Das ist bei uns nicht erlaubt. Alles nacheinander, keine Signale gleichzeitig.
Ist "place Charakter" eine Funktion? Die Gabel fehlt und die Funktion selber finde ich nicht als Diagramm.
Meintest du DOM Content Loaded mit "install load listener"(links oben)?
Eine Gute Arbeit mit ein paar Fehlern hier und da, aber du bist auf dem richtigen Weg und hast auf jeden Fall viel Zeit investiert.

**Comment by TobMer** [comment]
Danke für das Feedback.

Zu den 2 Pfeile bei dem Aktivitätsblubber : Da habe ich wahrscheinlich zu viel radiert. Falls du die meinst die zum Entscheidungsknoten führen.(Neben Data available) Ansonsten ist muss ich sagen, dass mir der Teil sehr schwer gefallen ist. Wie könnte ich denn die Signale gescheit nacheinander platzieren?

"place Charakter" : Ich wollte einen Button erschaffen, bei dem ich den Charakter den ich erschaffen habe bestätigen und auswählen möchte. Da war ich mir sicher, dass ich keine Gabel brauchen müsste und habe deshalb keine Funktion geschrieben. 

Install Load Listener: Darauf bin ich ausgegangen, dass dies der Syntax wie bei der Aufgabe mit der Cocktailbar ähnlich ist und ich das genauso machen könnte. 

Ich habe mir auf jedenfall am Wochenende Zeit genommen und mir nochmal die Videos angeschaut. Das Aktivitätsdiagramm fällt mir noch etwas schwer, da ich noch verstehen muss wie der Aufbau ist und wann und wie ich eine Funktion darstellen muss. Ich denke mit etwas Übung geht das hoffentlich bald. Vielen Dank.

**Comment by obiwan1337** [comment]
Aktivitaetsblubber >
Ich meine die Pfeile die von z.B.  printRow (item,BMI)
Da geht ein Pfeil zu KG/größe (links von print row)
und dann geht ein Pfeil nach unten zu einem anderen printRow.
Wenn du sowas machst, solltest du alles der Reihe nach ablaufen lassen. Also 
den BMI zuerst dann das Ergebnis, dann Entscheidungsknoten, dann das nächste (hier das Alter) dann das Ergebnis davon und ein neuer Entscheidungsknoten.
Es kann ja auch vorkommen, dass ein Ergebnis nicht ausgerechnet werden kann, weil ein Teil der Rechnung noch nicht eingetragen ist und das script damit schon rechnen will...
Dann kannst du auch eine "da kann ich nicht mit rechnen "Situation umgehen und das Script nippelt dir nicht auf dem Weg ab weil eine Zahl nicht da war.
Install Loader >
Der Load Listener im Code hat nicht nur eine Möglichkeit deswegen die Frage dazu. Es gibt einmal den Listener der auf das "geladen" wartet und den anderen der auf das "DOM Inhalt geladen" wartet. Beide sind dazu da um das Script richtig einzubinden und nicht ohne HTML-Elemente loslaufen zu lassen. Also deine Webseite wird aufgerufen und du hast keinen Listener angebracht, dann wird dein Javascript ausgeführt und hat noch keine Slider auf der Website zum Abhören und schmeißt dir eine Fehlermeldung und ist dann tot im Graben (abgestürzt).
Deswegen den Loaded-Listener. Der ist nicht falsch. Kannst du weiterhin so machen. Bei loaded musst du halt weniger schreiben deswegen nutzt der Prof. das lieber.

Ich versuche das hier so neutral wie möglich auf Sachen zu analysieren die noch nicht ganz richtig sind und Dir einen Tipp zu geben darauf zu achten beim nächsten mal. Und deine Arbeitsmühe habe ich durchaus bemerkt. Schon dein Interface-Diagramm hat einen sehr langen Zeitaufwand ausgestrahlt. Das mit den Aktivitätsdiagrammen kommt mit der Zeit... lass dich nicht entmutigen von ein paar Fehlern. war bei mir auch so am Anfang.
