### ISSUE TITLE
L05 JSON Chareditor

### ISSUE THREAD

**Issue by obiwan1337** [TobMer/EIA2#3]
Guten Mittag,

Also zu allererst ist es löblich das Du den Editor versucht hast umzusetzen:)
Deine TS Dateien hast du vergessen in JS umzuwandeln. 
Das machst du in VS Code wenn du auf "terminal" in der oberen Leiste gehst und build Task "watch" laufen laesst. Wenn der watch an ist wird bei jedem Seichern die JS neu uebersetzt aus deiner TS.
Das erklaert auch warum die zwei js Dateien nicht reinladen. Nicht wundern. 
Dein Konzept war wie Freitag schon gesagt umsetzbar mit evtl ein paar Problemen (passiert aber immer wieder)
Deine for in Schleife ist soweit richtig geschrieben. Versuche Dich doch evtl mal an einer Alten Aufgabe. Das Memory Konzept umsetzen ist doch ne Idee um in den Code reinzukommen. die Praktikanten im Labor sind genau dazu da also feel free to abuse them :p

**Comment by TobMer** [comment]
Die alte Aufgabe habe ich angeschaut aber es verwirrt mich dennoch wann ich wo was einsetze.
(╯°□°）╯︵ ┻━┻

Ich versuchs mal

**Comment by obiwan1337** [comment]
Welche alte Aufgabe ? Die mit den Karten?
